# Generated by Django 3.0.3 on 2020-02-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgs', '0003_auto_20200226_0143'),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rpg_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpgs.Rpg'),
        ),
    ]
