# Generated by Django 3.0.3 on 2020-02-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_rpg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='completed',
        ),
    ]
