# Generated by Django 3.0.3 on 2020-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgs', '0002_auto_20200226_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpg',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
