# Generated by Django 3.0.3 on 2020-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.TextField(default='mamador de bola', max_length=256),
            preserve_default=False,
        ),
    ]
