# Generated by Django 3.0.3 on 2020-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_rpg_id'),
        ('players', '0002_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(to='achievements.Achievement'),
        ),
    ]
