# Generated by Django 3.0.3 on 2020-02-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.TextField(default='12345', max_length=64),
        ),
    ]
